/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.chitietphieuBUS;
import BUS.chitietphieuphatBUS;
import BUS.docgiaBUS;
import BUS.nhanvienBUS;
import BUS.phieumuontraBUS;
import BUS.sachBUS;
import BUS.tinhtrangsachBUS;
import DTO.chitietphieuDTO;
import DTO.chitietphieuphatDTO;
import DTO.phieuphatDTO;
import DTO.sachDTO;
import interfaces.InSachSelect;
import interfaces.QueryCallBack;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.jdatepicker.impl.JDatePanelImpl;
import org.jdatepicker.impl.JDatePickerImpl;
import org.jdatepicker.impl.UtilDateModel;
import untils.CheckData;
import untils.DateLabelFormatter;
import untils.OutFile;

/**
 *
 * @author Admin
 */
public class PanelChiTietPhieuPhat extends javax.swing.JPanel implements QueryCallBack, InSachSelect {

    /**
     * Creates new form PanelLoanSlip
     */
    DefaultTableModel dtm;
    ArrayList<chitietphieuphatDTO> arr = new ArrayList<chitietphieuphatDTO>();
    ArrayList<chitietphieuphatDTO> tempsearch = new ArrayList<chitietphieuphatDTO>();
    JDatePickerImpl datePicker;
    JDatePickerImpl datePicker2;
    UtilDateModel model = new UtilDateModel();
    UtilDateModel model2 = new UtilDateModel();
    Panelchoosesach panelS;
    String maphieuphat;
    int type = 0;
    chitietphieuphatDTO current = new chitietphieuphatDTO();
    
    public PanelChiTietPhieuPhat(chitietphieuDTO chitiet, int type) {
        this.maphieuphat = chitiet.getMaMuonTra();
        this.type = type;
        arr = chitietphieuphatBUS.getChiTietPhieuPhat();
        
        initComponents();
        jButton15.setVisible(false);
        panelS = new Panelchoosesach(this);
        panelS.setBackground(new java.awt.Color(102, 102, 102));
        panelS.setForeground(new java.awt.Color(0, 204, 204));
        panelS.setLayout(null);
        panelS.setBounds(0, 0, 1024, 768);
        panelS.setVisible(false);
        add(panelS);
        
        Properties p = new Properties();
        p.put("text.today", "Today");
        p.put("text.month", "Month");
        p.put("text.year", "Year");
        
        JDatePanelImpl datePanel = new JDatePanelImpl(model, p);
        JDatePanelImpl datePane2 = new JDatePanelImpl(model2, p);
        
        datePicker = new JDatePickerImpl(datePanel, new DateLabelFormatter());
        datePicker.setBounds(10, 130, 120, 25);
        jPanel2.add(datePicker);
        
        datePicker2 = new JDatePickerImpl(datePane2, new DateLabelFormatter());
        datePicker2.setBounds(280, 130, 120, 25);
        jPanel2.add(datePicker2);
        initData();
        initEvent();
        loadChiTiet(chitiet.getMaMuonTra());
        if (!chitiet.getMaMuonTra().equals("oke")) {
            if (chitiet.getMaSach() != null) {
                tfsoluong.setEditable(false);
                buttonAddSach.setVisible(false);
                tfms.setText(sachBUS.getTenSach(chitiet.getMaSach()));
            }
            if (chitiet.getSoLuong() != null) {
                tfsoluong.setText(chitiet.getSoLuong() + "");
            }
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tfmaxchitiet = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        tfmapp = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        tfms = new javax.swing.JTextField();
        buttonAddSach = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        tfsoluong = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField6 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton9 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1165, 736));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setAutoscrolls(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin chi tiết phiếu phạt", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 0, 51))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setText("Chi tiết phiếu phạt");

        jButton1.setText("Mã Chi Tiết");

        jButton2.setText("Mã Phiếu Phạt");

        jButton3.setText("Mã Sách");

        buttonAddSach.setText("jButton9");
        buttonAddSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddSachActionPerformed(evt);
            }
        });

        jButton4.setText("Số Lượng");

        jButton5.setText("Tình Trạng");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trễ Hạn", "Mất Sách", "Rách Sách" }));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã Chi Tiết", "Mã Phiếu Phạt", "Tên Sách" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton10.setText("Tìm Kiếm");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton13.setText("Xuất Excel");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setText("Đọc Excel");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setText("Lưu ĐTB");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfmaxchitiet))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfmapp))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfms, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(buttonAddSach, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(41, 41, 41))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                                        .addGap(43, 43, 43))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton13)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(371, 371, 371)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfms, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonAddSach))
                        .addGap(7, 7, 7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tfmaxchitiet, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton13))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfmapp, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jButton14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton15)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thực hiện", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 0, 51))); // NOI18N

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("Thêm");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setText("Xóa");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setText("Sửa");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton11.setText("Back");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách chi tiết phiếu phạt", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 0, 102))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(40);
        jTable1.setRowMargin(10);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1039, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jButton9.setText("Xuất File PDF");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton12.setText("Xuất File Excel");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(1053, 1053, 1053)
                            .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(307, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        loadChiTiet(maphieuphat);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if (jButton8.getText().toString().equals("Sửa")) {
            tfsoluong.setEnabled(true);
            jButton8.setText("Xác nhận sửa");
            tfmaxchitiet.setEditable(false);
//            buttonAddSach.setVisible(true);

            jButton6.setVisible(false);
            jButton7.setVisible(false);
        } else {
            if (CheckData.checkNumber(tfsoluong.getText().toString().trim())) {
                tfsoluong.setEnabled(false);
//        jButton6.setVisible(true);
                jButton7.setVisible(true);
//            buttonAddSach.setVisible(false);
                jButton8.setText("Sửa");
                chitietphieuphatDTO ctp = new chitietphieuphatDTO();
                ctp.setMachitiet(tfmaxchitiet.getText().trim());
                ctp.setMaphieuphat(tfmapp.getText().trim());
                ctp.setMasach(current.getMasach());
                ctp.setSoluong(Integer.parseInt(tfsoluong.getText().trim()));
                ctp.setTinhtrangsach(jComboBox2.getSelectedIndex());
                ctp.setTienphat(Integer.parseInt(tfsoluong.getText().trim())
                        * (sachBUS.getDonGia(ctp.getMasach()) * tinhtrangsachBUS.getGiaPhat(ctp.getTinhtrangsach()) / 10));
                
                chitietphieuphatBUS.suaChiTietPhieuPhat(ctp, this);
            } else {
                JOptionPane.showMessageDialog(null, "Số lượng phải nhập số!");
            }
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        chitietphieuphatBUS.xoaChiTietPhieuPhat(tfmaxchitiet.getText().trim(), this);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (jButton6.getText().toString().equals("Thêm")) {
            tfsoluong.setEnabled(true);
            ArrayList<chitietphieuphatDTO> arr = chitietphieuphatBUS.getChiTietPhieuPhat();
            tfmaxchitiet.setText("" + (Integer.parseInt(arr.get(arr.size() - 1).getMachitiet()) + 1));
            jButton6.setText("Xác nhận thêm");
            buttonAddSach.setVisible(true);
            
            jButton7.setVisible(false);
            jButton8.setVisible(false);
            tfmapp.setText("");
            tfms.setText("");
            tfsoluong.setText("");
            jComboBox2.setSelectedIndex(0);
        } else {
            if (tfms.getText().length() == 0 || tfsoluong.getText().length() == 0 || jComboBox2.getSelectedItem() == "") {
                JOptionPane.showMessageDialog(null, "Vui lòng điền đủ thông tin cho chi tiết phiếu phạt");
            } else {
                if (CheckData.checkNumber(tfsoluong.getText().toString().trim())) {
                    tfsoluong.setEnabled(false);
                    jButton7.setVisible(true);
                    jButton8.setVisible(true);
                    buttonAddSach.setVisible(false);
                    jButton6.setText("Thêm");
                    chitietphieuphatDTO ctp = new chitietphieuphatDTO();
                    ctp.setMachitiet(tfmaxchitiet.getText().trim());
                    ctp.setMaphieuphat(tfmapp.getText().trim());
                    ctp.setMasach(current.getMasach());
                    ctp.setSoluong(Integer.parseInt(tfsoluong.getText().trim()));
                    ctp.setTinhtrangsach(jComboBox2.getSelectedIndex());
                    ctp.setTienphat(Integer.parseInt(tfsoluong.getText().trim())
                            * (sachBUS.getDonGia(ctp.getMasach()) * tinhtrangsachBUS.getGiaPhat(ctp.getTinhtrangsach()) / 10));
                    
                    chitietphieuphatBUS.themChiTietPhieuPhat(ctp, this);
                    if (type == 1) {
                        JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
                        topFrame.dispose();
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Số lượng phải nhập số!");
                }
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        String[] header = {"Mã Chi Tiết", "Mã Phiếu Phạt", "Tên Sách", "Số Lượng", "Tình Trạng", "Tiền Phạt"};
        DefaultTableModel dtmsearch = new DefaultTableModel(header, 0);
        ArrayList<chitietphieuphatDTO> s;
        if (jComboBox1.getSelectedItem() == "Mã Chi Tiết" || jComboBox1.getSelectedItem() == "Mã Phiếu Phạt") {
            if (CheckData.checkNumber(jTextField6.getText().toString().trim())) {
                s = chitietphieuphatBUS.timkiemChiTietPhieuPhat(String.valueOf(jComboBox1.getSelectedItem()), jTextField6.getText().toLowerCase().trim());                
            } else {
                JOptionPane.showMessageDialog(null, "Bạn phải nhập số!");
            }
        } else {
            s = chitietphieuphatBUS.timkiemChiTietPhieuPhat(String.valueOf(jComboBox1.getSelectedItem()), jTextField6.getText().toLowerCase().trim());
        }
        s = chitietphieuphatBUS.timkiemChiTietPhieuPhat(String.valueOf(jComboBox1.getSelectedItem()), jTextField6.getText().toLowerCase().trim());
        if (s.size() != 0) {
            chitietphieuphatDTO ctp = new chitietphieuphatDTO();
            for (int i = 0; i < s.size(); i++) {
                ctp = s.get(i);
                String machitiet = ctp.getMachitiet();
                String maphieuphat = ctp.getMaphieuphat();
                String tensach = sachBUS.getTenSach(ctp.getMasach());
                int soluong = ctp.getSoluong();
                int tinhtrang = ctp.getTinhtrangsach();
                int tienphat = ctp.getTienphat();
                Object[] row = {machitiet, maphieuphat, tensach, soluong, tinhtrangsachBUS.getTinhTrang(tinhtrang), tienphat};
                dtmsearch.addRow(row);
            }
            arr.clear();
            arr.addAll(tempsearch);
            tempsearch.clear();
            jTable1.setModel(dtmsearch);
            setView(s.get(0));
            jButton11.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Không có kết quả phù hợp!");
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void buttonAddSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddSachActionPerformed
        // TODO add your handling code here:
        jPanel2.setVisible(false);
        panelS.setVisible(true);
        revalidate();
    }//GEN-LAST:event_buttonAddSachActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        try {
            OutFile.writeExcel(jTable1, "system\\file\\excel\\chitietphieuphat\\", true);
        } catch (IOException ex) {
            Logger.getLogger(PanelBook.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            jTable1.setModel(OutFile.readExcel("system\\database\\data\\chitietphieuphat.xls"));
            jButton15.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(PanelChiTietPhieuPhat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        TableModel model = jTable1.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {
            chitietphieuphatDTO ctpp = new chitietphieuphatDTO();
            ctpp.setMaphieuphat(model.getValueAt(i, 1) + "");
            ctpp.setMasach(model.getValueAt(i, 2) + "");
            ctpp.setSoluong(Integer.parseInt(model.getValueAt(i, 3) + ""));
            ctpp.setTinhtrangsach(Integer.parseInt(model.getValueAt(i, 4) + ""));
            ctpp.setTienphat(Integer.parseInt(model.getValueAt(i, 5) + ""));
            chitietphieuphatBUS.themChiTietPhieuPhat(ctpp, this);
        }
        jButton15.setVisible(false);
    }//GEN-LAST:event_jButton15ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddSach;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField tfmapp;
    private javax.swing.JTextField tfmaxchitiet;
    private javax.swing.JTextField tfms;
    private javax.swing.JTextField tfsoluong;
    // End of variables declaration//GEN-END:variables

    private void loadChiTiet(String mamuontr) {
        
        String[] header = {"Mã Chi Tiết", "Mã Phiếu Phạt", "Tên Sách", "Số Lượng", "Tình Trạng", "Tiền Phạt"};
        
        dtm = new DefaultTableModel(header, 0);
        arr = chitietphieuphatBUS.getChiTietPhieuPhat();
        chitietphieuphatDTO ctp = new chitietphieuphatDTO();
        if (mamuontr.equals("oke")) {
            for (int i = 0; i < arr.size(); i++) {
                ctp = arr.get(i);
                String chitietmuontra = ctp.getMachitiet();
                String maphieuphats = ctp.getMaphieuphat();
                String tensach = sachBUS.getTenSach(ctp.getMasach());
                int soluong = ctp.getSoluong();
                int tienphat = ctp.getTienphat();
                int tinhtrang = ctp.getTinhtrangsach();
                // System.out.println(mamuontra + tensach + soluong + datra + ngaytra + hantra);
                Object[] row = {chitietmuontra, maphieuphats, tensach, soluong, tinhtrangsachBUS.getTinhTrang(tinhtrang), tienphat};
                dtm.addRow(row);
            }
            jTable1.setModel(dtm);
            setView(arr.get(0));
        } else {
            if (type == 0) {
                int k = -1;
                for (int i = arr.size() - 1; i >= 0; i--) {
                    if (!arr.get(i).getMaphieuphat().equals(maphieuphat)) {
                        arr.remove(i);
                    }
                    
                }
                for (int i = 0; i < arr.size(); i++) {
                    ctp = arr.get(i);
                    String chitietmuontra = ctp.getMachitiet();
                    String maphieuphats = ctp.getMaphieuphat();
                    String tensach = sachBUS.getTenSach(ctp.getMasach());
                    int soluong = ctp.getSoluong();
                    int tinhtrang = ctp.getTinhtrangsach();
                    int tienphat = ctp.getTienphat();
                    // System.out.println(mamuontra + tensach + soluong + datra + ngaytra + hantra);
                    if (maphieuphats.equals(maphieuphat)) {
                        if (k == -1) {
                            k = i;
                        }
                        Object[] row = {chitietmuontra, maphieuphat, tensach, soluong, tinhtrangsachBUS.getTinhTrang(tinhtrang), tienphat};
                        dtm.addRow(row);
                    }
                    
                }
                jTable1.setModel(dtm);
                setView(arr.get(k));
                
            } else {
                jButton6.setVisible(true);
                for (int i = 0; i < arr.size(); i++) {
                    ctp = arr.get(i);
                    String chitietmuontra = ctp.getMachitiet();
                    String maphieuphat = ctp.getMaphieuphat();
                    String tensach = sachBUS.getTenSach(ctp.getMasach());
                    int soluong = ctp.getSoluong();
                    int tienphat = ctp.getTienphat();
                    int tinhtrang = ctp.getTinhtrangsach();
                    // System.out.println(mamuontra + tensach + soluong + datra + ngaytra + hantra);
                    Object[] row = {chitietmuontra, maphieuphat, tensach, soluong, tinhtrangsachBUS.getTinhTrang(tinhtrang), tienphat};
                    dtm.addRow(row);
                }
                jTable1.setModel(dtm);
                setView(arr.get(0));
                jButton6.doClick();
                tfmapp.setText(mamuontr);
            }
        }
    }
    
    public void setView(chitietphieuphatDTO ctp) {
        if (jButton8.getText().equals("Sửa")) {
            tfmaxchitiet.setText(ctp.getMachitiet() + "");
            tfmapp.setText(ctp.getMaphieuphat());
            tfms.setText(sachBUS.getTenSach(ctp.getMasach()));
            tfsoluong.setText(ctp.getSoluong() + "");
            jComboBox2.setSelectedIndex(ctp.getTinhtrangsach());
            current.setMasach(ctp.getMasach());
        }
//        tftienphat.setText(ctp.getTienphat()+"");
    }
    
    private void initData() {
        tfsoluong.setEnabled(false);
        buttonAddSach.setVisible(false);
        datePicker.setVisible(false);
        datePicker2.setVisible(false);
        jButton11.setVisible(false);
        tfms.setEditable(false);
        tfmapp.setEditable(false);
        tfmaxchitiet.setEditable(false);
        jButton6.setVisible(false);
    }
    
    private void initEvent() {
        jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent event) {
                try {
                    if (type == 0) {
                        System.err.println("" + arr.size());
                        setView(arr.get(jTable1.getSelectedRow()));
                    }
                } catch (Exception e) {
                }
            }
        });
        
    }
    
    @Override
    public void onSuccess() {
        loadChiTiet(maphieuphat);
    }
    
    @Override
    public void onFailed(String error) {
        tfmaxchitiet.setText(error);
    }
    
    @Override
    public void sach(sachDTO tg) {
        
        tfms.setText(tg.getTenSach());
        current.setMasach(tg.getMaSach());
        jPanel2.setVisible(true);
        panelS.setVisible(false);
    }
}
