/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.chitietphieunhapBUS;
import BUS.sachBUS;
import DTO.chitietphieunhapDTO;
import DTO.chitietphieuphatDTO;
import DTO.sachDTO;
import interfaces.InSachSelect;
import interfaces.QueryCallBack;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.jdatepicker.impl.JDatePanelImpl;
import org.jdatepicker.impl.JDatePickerImpl;
import org.jdatepicker.impl.UtilDateModel;
import untils.CheckData;
import untils.DateLabelFormatter;
import untils.OutFile;

/**
 *
 * @author Admin
 */
public class PanelChiTietPhieuNhap extends javax.swing.JPanel implements QueryCallBack,InSachSelect{

    /**
     * Creates new form PanelLoanSlip
     */
    DefaultTableModel dtm;
    ArrayList<chitietphieunhapDTO> arr = new ArrayList<chitietphieunhapDTO>();
    JDatePickerImpl datePicker;
    JDatePickerImpl datePicker2;
    UtilDateModel model = new UtilDateModel();
    UtilDateModel model2 = new UtilDateModel();
    Panelchoosesach panelS;
    String maphieuphat;
    chitietphieunhapDTO current = new chitietphieunhapDTO();
    int type=0;

    public PanelChiTietPhieuNhap(String maphieuphat,int type) {
        this.maphieuphat=maphieuphat;
        this.type=type;
        arr = chitietphieunhapBUS.getChiTietPhieuNhap();
        initComponents();
        
        panelS= new Panelchoosesach(this);
        panelS.setBackground(new java.awt.Color(102, 102, 102));
        panelS.setForeground(new java.awt.Color(0, 204, 204));
        panelS.setLayout(null);
        panelS.setBounds(0, 0, 1024, 768);
        panelS.setVisible(false);
        add(panelS);
        
        
        
        
        Properties p = new Properties();
        p.put("text.today", "Today");
        p.put("text.month", "Month");
        p.put("text.year", "Year");

        JDatePanelImpl datePanel = new JDatePanelImpl(model, p);
        JDatePanelImpl datePane2 = new JDatePanelImpl(model2, p);

        datePicker = new JDatePickerImpl(datePanel, new DateLabelFormatter());
        datePicker.setBounds(10, 130, 120, 25);
        jPanel2.add(datePicker);

        datePicker2 = new JDatePickerImpl(datePane2, new DateLabelFormatter());
        datePicker2.setBounds(280, 130, 120, 25);
        jPanel2.add(datePicker2);
        initData();
        initEvent();
        loadChiTiet(maphieuphat,type);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tfmaxchitiet = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        tfmapp = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        tfms = new javax.swing.JTextField();
        buttonAddSach = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        tfsoluong = new javax.swing.JTextField();
        buttondongia = new javax.swing.JButton();
        tfdongia = new javax.swing.JTextField();
        buttonthanhtien = new javax.swing.JButton();
        tfthanhtien = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<String>();
        jTextField6 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1082, 700));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1079, 700));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin phiếu nhập", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 153))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Chi tiết phiếu nhập");

        jButton1.setText("Mã Chi Tiết");

        jButton2.setText("Mã Phiếu Nhập");

        jButton3.setText("Mã Sách");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        buttonAddSach.setText("jButton9");
        buttonAddSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddSachActionPerformed(evt);
            }
        });

        jButton4.setText("Số Lượng");

        buttondongia.setText("Đơn Giá");
        buttondongia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttondongiaActionPerformed(evt);
            }
        });

        buttonthanhtien.setText("Thành Tiền");

        tfthanhtien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfthanhtienActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mã Chi Tiết", "Mã Phiếu Nhập", "Mã Sách" }));

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton10.setText("Tìm Kiếm");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton12.setText("Xuất Excel");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton5.setText("Đọc Excel");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton9.setText("Lưu ĐTB");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfmaxchitiet, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfmapp, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(buttondongia, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tfdongia, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(buttonthanhtien, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tfthanhtien, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(5, 5, 5))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfms, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buttonAddSach, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton12)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton5)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton9)))))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfmaxchitiet, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfmapp, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttondongia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfdongia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfms, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonthanhtien, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttonAddSach)
                                .addComponent(tfthanhtien, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton12)
                                .addComponent(jButton5)
                                .addComponent(jButton9)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thực hiện", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 0, 51))); // NOI18N

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("Thêm");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setText("Xóa");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setText("Sửa");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton11.setText("Back");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                    .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách chi tiết phiếu nhập", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 102, 102))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(40);
        jTable1.setRowMargin(10);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1011, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 431, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

        String[] header = {"Mã Chi Tiết", "Mã Phiếu Nhập", "Tên Sách", "Số Lượng", "Đơn Giá", "Thành Tiền"};
        DefaultTableModel dtmsearch = new DefaultTableModel(header, 0);
        ArrayList<chitietphieunhapDTO> s;

        s = chitietphieunhapBUS.timkiemChiTietPhieuNhap(String.valueOf(jComboBox1.getSelectedItem()), jTextField6.getText().toLowerCase().trim());
        if (s.size() != 0) {
            chitietphieunhapDTO ctp = new chitietphieunhapDTO();
            for (int i = 0; i < s.size(); i++) {
                ctp = s.get(i);
                String machitiet = ctp.getMachitiet();
                String maphieunhap = ctp.getMaphieunhap();
                String tensach = sachBUS.getTenSach(ctp.getMasach());
                int soluong = ctp.getSoluong();
                int dongia = sachBUS.getDonGia(ctp.getMasach());
                int thanhtien = ctp.getThanhtien();
                Object[] row = {machitiet,maphieunhap,tensach, soluong, dongia, thanhtien};
                dtmsearch.addRow(row);
            }
            jTable1.setModel(dtmsearch);
            setView(s.get(0));
            jButton11.setVisible(true);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void tfthanhtienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfthanhtienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfthanhtienActionPerformed

    private void buttondongiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttondongiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttondongiaActionPerformed

    private void buttonAddSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddSachActionPerformed
        // TODO add your handling code here:
        jPanel2.setVisible(false);
        panelS.setVisible(true);
        revalidate();
    }//GEN-LAST:event_buttonAddSachActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        loadChiTiet(maphieuphat,0);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if (jButton8.getText().toString().equals("Sửa")) {
            jButton8.setText("Xác nhận sửa");

            tfdongia.setVisible(false);
            buttondongia.setVisible(false);
            tfthanhtien.setVisible(false);
            buttonthanhtien.setVisible(false);
            buttonAddSach.setVisible(true);
            
            jButton7.setVisible(false);
        } else {
            if(tfms.getText().length()==0||tfsoluong.getText().length()==0){
                JOptionPane.showMessageDialog(null, "Vui lòng điền đủ thông tin cho chi tiết phiếu nhập");
            }else{
                
            jButton7.setVisible(true);
                tfdongia.setVisible(true);
                buttondongia.setVisible(true);
                tfthanhtien.setVisible(true);
                buttonthanhtien.setVisible(true);
                buttonAddSach.setVisible(false);

                jButton8.setText("Sửa");
                chitietphieunhapDTO ctp = new chitietphieunhapDTO();
                ctp.setMachitiet(tfmaxchitiet.getText().trim());
                ctp.setMaphieunhap(tfmapp.getText().trim());
                ctp.setMasach(current.getMasach());
                ctp.setSoluong(Integer.parseInt(tfsoluong.getText().trim()));
                ctp.setThanhtien(Integer.parseInt(tfsoluong.getText().trim())
                    *(sachBUS.getDonGia(ctp.getMasach())));

                ctp.setDongia(sachBUS.getDonGia(ctp.getMasach()));

                chitietphieunhapBUS.suaChiTietPhieuPhat(ctp, this);
            }
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        chitietphieunhapBUS.xoaChiTietPhieuPhat(tfmaxchitiet.getText().trim(), this);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (jButton6.getText().toString().equals("Thêm")) {
            ArrayList<chitietphieunhapDTO> arr = chitietphieunhapBUS.getChiTietPhieuNhap();
            tfmaxchitiet.setText("" + (Integer.parseInt(arr.get(arr.size() - 1).getMachitiet()) + 1));
            jButton6.setText("Xác nhận thêm");
            tfmapp.setText("");
            tfms.setText("");
            jButton7.setVisible(false);
            jButton8.setVisible(false);
            tfsoluong.setText("");
            tfdongia.setVisible(false);
            buttondongia.setVisible(false);
            tfthanhtien.setVisible(false);
            buttonthanhtien.setVisible(false);
            buttonAddSach.setVisible(true);
            tfdongia.setText("");
            tfthanhtien.setText("");
        } else {
            if(tfms.getText().length()==0||tfsoluong.getText().length()==0){
                JOptionPane.showMessageDialog(null, "Vui lòng điền đủ thông tin cho chi tiết phiếu nhập");
            }else{
                 if (CheckData.checkNumber(tfsoluong.getText().toString().trim()))
                {
            jButton7.setVisible(true);
            jButton8.setVisible(true);
                tfdongia.setVisible(true);
                buttondongia.setVisible(true);
                tfthanhtien.setVisible(true);
                buttonthanhtien.setVisible(true);
                buttonAddSach.setVisible(false);
               
                jButton6.setText("Thêm");
                chitietphieunhapDTO ctp = new chitietphieunhapDTO();
                ctp.setMachitiet(tfmaxchitiet.getText().trim());
                ctp.setMaphieunhap(tfmapp.getText().trim());
                ctp.setMasach(current.getMasach());
                ctp.setSoluong(Integer.parseInt(tfsoluong.getText().trim()));
                ctp.setDongia(sachBUS.getDonGia(ctp.getMasach()));
                ctp.setThanhtien(Integer.parseInt(tfsoluong.getText().trim())
                    *(sachBUS.getDonGia(ctp.getMasach())));

                chitietphieunhapBUS.themChiTietPhieuNhap(ctp, this);
                type=1;
//                sachBUS.suaSach(ctp.getMasach(),ctp.getSoluong());
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Số lượng phải nhập số!");
                    type=0;
                }
                if(type==1){
                    JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
                    topFrame.dispose();
                }
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
         try {
            OutFile.writeExcel(jTable1, "system\\file\\excel\\chitietphieunhap\\", true);
        } catch (IOException ex) {
            Logger.getLogger(PanelBook.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            // TODO add your handling code here:
            jTable1.setModel(OutFile.readExcel("system\\database\\data\\chitietphieunhap.xls"));
            jButton9.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(PanelChiTietPhieuNhap.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
TableModel model= jTable1.getModel();
       for(int i=0;i<model.getRowCount();i++)
       {
           chitietphieunhapDTO ctpn=new chitietphieunhapDTO();
           ctpn.setMaphieunhap(model.getValueAt(i,1)+"");
           ctpn.setMasach(model.getValueAt(i,2)+"");
           ctpn.setSoluong(Integer.parseInt(model.getValueAt(i,3)+""));
           ctpn.setDongia(Integer.parseInt(model.getValueAt(i,4)+""));
           ctpn.setThanhtien(Integer.parseInt(model.getValueAt(i,5)+""));
           chitietphieunhapBUS.themChiTietPhieuNhap(ctpn, this);
       }
        // TODO add your handling code here:
        jButton9.setVisible(false);
    }//GEN-LAST:event_jButton9ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddSach;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttondongia;
    private javax.swing.JButton buttonthanhtien;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField tfdongia;
    private javax.swing.JTextField tfmapp;
    private javax.swing.JTextField tfmaxchitiet;
    private javax.swing.JTextField tfms;
    private javax.swing.JTextField tfsoluong;
    private javax.swing.JTextField tfthanhtien;
    // End of variables declaration//GEN-END:variables

    private void loadChiTiet(String mamuontr,int type) {
       
        String[] header = {"Mã Chi Tiết","Mã Phiếu Nhập", "Tên Sách", "Số Lượng", "Đơn Giá", "Thành Tiền"};
        
        dtm = new DefaultTableModel(header, 0);
        arr = chitietphieunhapBUS.getChiTietPhieuNhap();
        chitietphieunhapDTO ctp = new chitietphieunhapDTO();
        if(mamuontr==null){
        for (int i = 0; i < arr.size(); i++) {
            ctp = arr.get(i);
            String chitietmuontra = ctp.getMachitiet();
            String maphieunhap = ctp.getMaphieunhap();
            String tensach = sachBUS.getTenSach(ctp.getMasach());
            int soluong = ctp.getSoluong();
            int dongia = ctp.getDongia();
            int thanhtien = ctp.getThanhtien();
           // System.out.println(mamuontra + tensach + soluong + datra + ngaytra + hantra);
            Object[] row = {chitietmuontra,maphieunhap, tensach, soluong,dongia,thanhtien};
            dtm.addRow(row);
        }
        jTable1.setModel(dtm);
        setView(arr.get(0));
        }else{
            if(type==0){
                  for (int i = arr.size()-1; i>=0; i--) {
               if(!arr.get(i).getMaphieunhap().equals(maphieuphat)){
                   arr.remove(i);
               }
                
             }
                int k=-1;
            for (int i = 0; i < arr.size(); i++) {
            ctp = arr.get(i);
            String chitietmuontra = ctp.getMachitiet();
            String maphieuphats = ctp.getMaphieunhap();
            String tensach = sachBUS.getTenSach(ctp.getMasach());
            int soluong = ctp.getSoluong();
            int dongia = ctp.getDongia();
            int thanhtien = ctp.getThanhtien();
           // System.out.println(mamuontra + tensach + soluong + datra + ngaytra + hantra);
            if(maphieuphats.equals(maphieuphat)){
                if(k==-1){
                    k=i;
                }
            Object[] row = {chitietmuontra,maphieuphats, tensach, soluong,dongia, thanhtien};
                dtm.addRow(row);
            }
           
            }
                jTable1.setModel(dtm);
                setView(arr.get(k));
            }else{
                
        jButton6.setVisible(true);
                 for (int i = 0; i < arr.size(); i++) {
            ctp = arr.get(i);
            String chitietmuontra = ctp.getMachitiet();
            String maphieunhap = ctp.getMaphieunhap();
            String tensach = sachBUS.getTenSach(ctp.getMasach());
            int soluong = ctp.getSoluong();
            int dongia = ctp.getDongia();
            int thanhtien = ctp.getThanhtien();
           // System.out.println(mamuontra + tensach + soluong + datra + ngaytra + hantra);
            Object[] row = {chitietmuontra,maphieunhap, tensach, soluong,dongia,thanhtien};
            dtm.addRow(row);
        }
        jTable1.setModel(dtm);
        setView(arr.get(0));
            jButton6.doClick();
            tfmapp.setText(mamuontr);
            tfmaxchitiet.setEditable(false);
            tfmapp.setEditable(false);
            tfms.setEditable(false);
            tfdongia.setEditable(false);
            tfthanhtien.setEditable(false);
            }
            
        }
    }

    public void setView(chitietphieunhapDTO ctp) {
        if (jButton6.getText().equals("Thêm") && jButton8.getText().equals("Sửa")) {
            tfmaxchitiet.setText(ctp.getMachitiet()+ "");
        }
        tfmapp.setText(ctp.getMaphieunhap());
        tfms.setText(sachBUS.getTenSach(ctp.getMasach()));
        tfsoluong.setText(ctp.getSoluong()+"");
        tfdongia.setText(ctp.getDongia()+"");
        tfthanhtien.setText(ctp.getThanhtien()+"");
        current.setMasach(ctp.getMasach());
//        tftienphat.setText(ctp.getTienphat()+"");
    }

    private void initData() {
        datePicker.setVisible(false);
        datePicker2.setVisible(false);
        jButton11.setVisible(false);
        buttonAddSach.setVisible(false);
        tfmaxchitiet.setEditable(false);
        tfmapp.setEditable(false);
        tfdongia.setEditable(false);
        tfthanhtien.setEditable(false);
        tfms.setEditable(false);
        jButton6.setVisible(false);
        
    }

    private void initEvent() {
        jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent event) {
                try {
                    if(type==0){
                    setView(arr.get(jTable1.getSelectedRow()));
                    }
                } catch (Exception e) {
                }
            }
        });
       
    }

    @Override
    public void onSuccess() {
        loadChiTiet(maphieuphat,0);
        
    }

    @Override
    public void onFailed(String error) {
        tfmaxchitiet.setText(error);
    }

    @Override
    public void sach(sachDTO tg) {
        tfms.setText(tg.getTenSach());
        jPanel2.setVisible(true);
        panelS.setVisible(false);
        current.setMasach(tg.getMaSach());
    }
}
