/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.docgiaBUS;
import BUS.nhanvienBUS;
import BUS.tacgiaBUS;
import BUS.theloaiBus;
import DTO.docgiaDTO;
import DTO.nhanvienDTO;
import DTO.tacgiaDTO;
import DTO.theloaiDTO;
import interfaces.InDocGiaSelect;
import interfaces.InNhanVienSelect;
import interfaces.InTacGiaSelect;
import interfaces.InTheLoaiSelect;
import interfaces.QueryCallBack;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Panelchoosenhanvien extends javax.swing.JPanel implements QueryCallBack{
    DefaultTableModel dtm;
    ArrayList<nhanvienDTO> arr= new ArrayList<nhanvienDTO>();
    nhanvienDTO current = new nhanvienDTO();
    InNhanVienSelect inNhanVienSelect;
    /**
     * Creates new form PanelTacGia
     */
    public Panelchoosenhanvien(InNhanVienSelect inNhanVienSelect) {
        initComponents();
        loadTheLoai();
        initEvent();
        buttonChon.setVisible(false);
        this.inNhanVienSelect = inNhanVienSelect;
        
    }
    private void initEvent() {
        jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
        public void valueChanged(ListSelectionEvent event) {
            // do some actions here, for example
            // print first column value from selected row
            try {
                
            current.setMaNV(arr.get(jTable1.getSelectedRow()).getMaNV());
            current.setTenNhanVien(arr.get(jTable1.getSelectedRow()).getTenNhanVien());
            } catch (Exception e) {
            }
           if(!buttonChon.isVisible()){
               buttonChon.setVisible(true);
           }
        }
        });
     
    }
    
    public void loadTheLoai(){
        String[] header = {"Mã Nhân Viên","Tên Nhân Viên"};
        
        dtm = new DefaultTableModel(header,0);
        arr = nhanvienBUS.getNhanVien();
        nhanvienDTO s = new nhanvienDTO();
        for(int i = 0; i < arr.size(); i++){
            s = arr.get(i);
            String matl =  s.getMaNV();
            String tentl = s.getTenNhanVien();
            Object[] row = {matl,tentl};
            dtm.addRow(row);
        }
        jTable1.setModel(dtm);
//        setView(arr.get(0));
       
         
       
       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonChon = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(825, 575));
        setLayout(null);

        buttonChon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonChon.setText("Chọn");
        buttonChon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonChonActionPerformed(evt);
            }
        });
        add(buttonChon);
        buttonChon.setBounds(0, 494, 115, 59);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách nhân viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 51, 0))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(40);
        jTable1.setRowMargin(10);
        jTable1.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel1);
        jPanel1.setBounds(0, 0, 1020, 480);

        jButton1.setText("Xuất File PDF");
        add(jButton1);
        jButton1.setBounds(133, 494, 150, 59);

        jButton2.setText("Xuất File Excel");
        add(jButton2);
        jButton2.setBounds(301, 494, 150, 59);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonChonActionPerformed
        // TODO add your handling code here:
        inNhanVienSelect.nhanvien(current);
    }//GEN-LAST:event_buttonChonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonChon;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onSuccess() {
        loadTheLoai();
    }

    @Override
    public void onFailed(String error) {
        System.err.println(""+error);
    }
}
