/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.docgiaBUS;
import BUS.nhanvienBUS;
import BUS.sachBUS;
import BUS.tacgiaBUS;
import BUS.theloaiBus;
import DTO.docgiaDTO;
import DTO.nhanvienDTO;
import DTO.sachDTO;
import DTO.tacgiaDTO;
import DTO.theloaiDTO;
import interfaces.InDocGiaSelect;
import interfaces.InNhanVienSelect;
import interfaces.InSachSelect;
import interfaces.InTacGiaSelect;
import interfaces.InTheLoaiSelect;
import interfaces.QueryCallBack;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Panelchoosesach extends javax.swing.JPanel implements QueryCallBack{
    DefaultTableModel dtm;
    ArrayList<sachDTO> arr= new ArrayList<sachDTO>();
    sachDTO current = new sachDTO();
    InSachSelect inSachSelect;
    /**
     * Creates new form PanelTacGia
     */
    public Panelchoosesach(InSachSelect inSachSelect) {
        initComponents();
        loadTheLoai();
        initEvent();
        buttonChon.setVisible(false);
        this.inSachSelect = inSachSelect;
        
    }
    private void initEvent() {
        jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
        public void valueChanged(ListSelectionEvent event) {
            // do some actions here, for example
            // print first column value from selected row
            try {
                
            current.setMaSach(arr.get(jTable1.getSelectedRow()).getMaSach());
            current.setTenSach(arr.get(jTable1.getSelectedRow()).getTenSach());
            } catch (Exception e) {
            }
           if(!buttonChon.isVisible()){
               buttonChon.setVisible(true);
           }
        }
        });
     
    }
    
    public void loadTheLoai(){
        String[] header = {"Mã Sách","Tên Sách"};
        
        dtm = new DefaultTableModel(header,0);
        arr = sachBUS.getSach();
        sachDTO s = new sachDTO();
        for(int i = 0; i < arr.size(); i++){
            s = arr.get(i);
            String matl =  s.getMaSach();
            String tentl = s.getTenSach();
            Object[] row = {matl,tentl};
            dtm.addRow(row);
        }
        jTable1.setModel(dtm);
//        setView(arr.get(0));
       
         
       
       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonChon = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(820, 610));
        setLayout(null);

        buttonChon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonChon.setText("Chọn");
        buttonChon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonChonActionPerformed(evt);
            }
        });
        add(buttonChon);
        buttonChon.setBounds(174, 520, 158, 72);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Quản Lý Sách");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(0, 520, 164, 72);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách Sách", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 51, 0))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(40);
        jTable1.setRowMargin(10);
        jTable1.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel1);
        jPanel1.setBounds(0, 0, 1020, 500);

        jButton2.setText("Xuất File PDF");
        add(jButton2);
        jButton2.setBounds(350, 520, 156, 72);

        jButton3.setText("Xuất File Excel");
        add(jButton3);
        jButton3.setBounds(524, 520, 155, 72);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonChonActionPerformed
        // TODO add your handling code here:
        inSachSelect.sach(current);
    }//GEN-LAST:event_buttonChonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        JFrame addSach = new JFrame();
         addSach.setVisible(true);
         Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
         addSach.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
         addSach.setSize(1044, 768);
          addSach.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosing(java.awt.event.WindowEvent windowEvent) {
            loadTheLoai();
            System.err.println("ádasdas");
        }
    });
         PanelBook pb = new PanelBook();
         pb.setBounds(0,0,1024,768);
         addSach.add(pb);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonChon;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onSuccess() {
        loadTheLoai();
    }

    @Override
    public void onFailed(String error) {
        System.err.println(""+error);
    }
}
