/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.nhaccBUS;
import DAO.nhaccDAO;
import DTO.nhaccDTO;
import DTO.tacgiaDTO;
import interfaces.InNhaCCSelect;
import interfaces.InTacGiaSelect;
import interfaces.QueryCallBack;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class PanelNhaCC extends javax.swing.JPanel implements QueryCallBack{
    DefaultTableModel dtm;
    ArrayList<nhaccDTO> arr= new ArrayList<nhaccDTO>();
    nhaccDTO current = new nhaccDTO();
    InNhaCCSelect inNhaCCSelect;
    /**
     * Creates new form PanelTacGia
     */
    public PanelNhaCC(InNhaCCSelect inNhaCCSelect) {
        initComponents();
        loadTacGia();
        initEvent();
        buttonChon.setVisible(false);
        this.inNhaCCSelect = inNhaCCSelect;
        
    }
    private void initEvent() {
        jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
        public void valueChanged(ListSelectionEvent event) {
            // do some actions here, for example
            // print first column value from selected row
            try {
                
            current.setMancc(arr.get(jTable1.getSelectedRow()).getMancc());
            current.setTenncc(arr.get(jTable1.getSelectedRow()).getTenncc());
            current.setDiachi(arr.get(jTable1.getSelectedRow()).getDiachi());
            current.setSdt(arr.get(jTable1.getSelectedRow()).getSdt());
            } catch (Exception e) {
            }
           if(!buttonChon.isVisible()){
               buttonChon.setVisible(true);
           }
        }
        });
     
    }
    
    public void loadTacGia(){
        String[] header = {"Mã Nhà Cung Cấp","Tên Nhà Cung Cấp","Địa Chỉ","SĐT"};
        
        dtm = new DefaultTableModel(header,0);
        arr = nhaccBUS.getNhaCC();
        nhaccDTO s = new nhaccDTO();
        for(int i = 0; i < arr.size(); i++){
            s = arr.get(i);
            String matg =  s.getMancc();
            String tentg = s.getTenncc();
            String diachi = s.getDiachi();
            String sdt = s.getSdt();
            Object[] row = {matg,tentg,diachi,sdt};
            dtm.addRow(row);
        }
        jTable1.setModel(dtm);
//        setView(arr.get(0));
       
         
       
       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        buttonChon = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(786, 432));
        setLayout(null);
        add(jPanel1);
        jPanel1.setBounds(1677, 0, 10, 10);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Thực hiện"));
        jPanel2.setForeground(new java.awt.Color(204, 0, 0));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Thêm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Xóa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Sửa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonChon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonChon.setText("Chọn");
        buttonChon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonChonActionPerformed(evt);
            }
        });

        jButton5.setText("Xuất File PDF");

        jButton4.setText("Xuất File Excel");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonChon, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonChon, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        add(jPanel2);
        jPanel2.setBounds(1, 0, 183, 489);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách nhà cung cấp"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(40);
        jTable1.setRowMargin(10);
        jTable1.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
        );

        add(jPanel3);
        jPanel3.setBounds(190, 0, 830, 490);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonChonActionPerformed
        // TODO add your handling code here:
        inNhaCCSelect.nhacc(current);
    }//GEN-LAST:event_buttonChonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
           String name = JOptionPane.showInputDialog(this, "Nhập Tên Nhà Cung Cấp");
          if(name !=null){
              current.setTenncc(name.trim());
             ArrayList<nhaccDTO> arr = nhaccBUS.getNhaCC();
              current.setMancc((Integer.parseInt(arr.get(arr.size()-1).getMancc())+1)+"");
//              nxbBUS.themNXB(current, this);
             String diachi = JOptionPane.showInputDialog(this, "Nhập Địa Chỉ Nhà Cung Cấp");
            if(diachi!=null){
              current.setDiachi(diachi.trim());
             
               String sdt = JOptionPane.showInputDialog(this, "Nhập Sđt Nhà Xuất Bản");
             if(sdt!=null){
              current.setSdt(sdt.trim());
                 nhaccBUS.themTacgia(current, this);
            }
            }
          }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(current.getMancc().length()>0){
            nhaccBUS.xoaTacgia(current.getMancc(), this);
            System.err.println("okme");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            String name = JOptionPane.showInputDialog(this, "Nhập Tên Nhà Cung Cấp",current.getTenncc());
          if(name !=null){
              current.setTenncc(name.trim());
             String diachi = JOptionPane.showInputDialog(this, "Nhập Địa Chỉ Nhà Cung Cấp",current.getDiachi());
            if(diachi!=null){
              current.setDiachi(diachi.trim());
               String sdt = JOptionPane.showInputDialog(this, "Nhập Sđt Nhà Xuất Bản",current.getSdt());
             if(sdt!=null){
              current.setSdt(sdt.trim());
                nhaccBUS.suaTacgia(current, this);
            }
            }
          }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonChon;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onSuccess() {
        loadTacGia();
    }

    @Override
    public void onFailed(String error) {
        System.err.println(""+error);
    }
}
